[package]
name = "testing-with-alloy"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.12", features = ["full", "node-bindings"]}
eyre = "0.6.12"
tokio = { version = "1.45.1", features = ["full"]}
